# Generated by Django 5.2.1 on 2025-05-31 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='female',
            name='relationship',
        ),
        migrations.AddField(
            model_name='male',
            name='relationship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.female'),
        ),
    ]
