# Generated by Django 5.2.1 on 2025-05-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_alter_male_relationship_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='watch',
            field=models.ManyToManyField(null=True, to='pages.video'),
        ),
    ]
