# Generated by Django 5.2.1 on 2025-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Homes', 'Homes'), ('Toys', 'Toys'), ('Decoration', 'Decoration'), ('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Sports', 'Sports'), ('Beauty', 'Beauty'), ('Food', 'Food'), ('Health', 'Health'), ('Automotive', 'Automotive'), ('Garden', 'Garden'), ('Tools', 'Tools'), ('Pet Supplies', 'Pet Supplies'), ('Office Supplies', 'Office Supplies')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/%y/%m/%d', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
