# Generated by Django 5.2.1 on 2025-05-31 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_time_alter_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='time',
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
